const poly = (id: string) => `/assets/models/polyhaven/${id}/${id}_1k.gltf`;
const supplied = "/assets/local-only/original";

export const ASSETS = {
  shotgun: "/assets/models/shotgun.glb",
  dealer: "/assets/models/vibapop-dealer/The%20Dealer.fbx",
  dealerTexture: "/assets/models/vibapop-dealer/The%20Dealer%20Texture.png",
  dealerItemsTexture: "/assets/models/vibapop-dealer/Items%20Texture.png",
  dealerItemsEmission: "/assets/models/vibapop-dealer/Items%20Emission.png",
  itemModels: {
    magnifier: poly("magnifying_glass_01"),
    cigarettes: poly("cigarette_pack"),
    handSaw: poly("handsaw_wood"),
  },
  textures: {
    felt: `${supplied}/textures/felt.png`,
    feltShellRack: `${supplied}/textures/felt-shell-rack.png`,
    brick: `${supplied}/textures/brick.png`,
    rust: `${supplied}/textures/rust.png`,
    wood: `${supplied}/textures/wood.png`,
    magnifier: `${supplied}/textures/magnifier.png`,
    beer: `${supplied}/textures/beer.png`,
    cigarettesFront: `${supplied}/textures/cigarettes-front.png`,
    cigarettesSide: `${supplied}/textures/cigarettes-side.png`,
    handcuffs: `${supplied}/textures/handcuffs.png`,
    handSaw: `${supplied}/textures/hand-saw.png`,
    burnerPhone: `${supplied}/textures/burner-phone.png`,
    inverter: `${supplied}/textures/inverter.png`,
    expiredMedicine: `${supplied}/textures/expired-medicine.png`,
    adrenaline: `${supplied}/textures/adrenaline.png`,
    dealerSkin: `${supplied}/textures/dealer-skin.png`,
    dealerHands: `${supplied}/textures/dealer-hands.png`,
    shotgunWood: `${supplied}/textures/shotgun-wood.png`,
    shotgunMetal: `${supplied}/textures/shotgun-metal.png`,
    briefcaseCarbon: `${supplied}/textures/briefcase-carbon.png`,
    briefcaseSteel: `${supplied}/textures/briefcase-steel.png`,
    shellLive: `${supplied}/textures/shell-live.png`,
    shellBlank: `${supplied}/textures/shell-blank.png`,
    restroomTiles: `${supplied}/textures/intro/restroom1_tiles broken 1024 albedo.png`,
    restroomWallTiles: `${supplied}/textures/restroom/restroom1_tiles normal 2048.png`,
    restroomWallNormal: `${supplied}/textures/restroom/restroom1_tilies normal 2048 normal map.png`,
    restroomCeramic: `${supplied}/textures/restroom/restroom1_ceramic 1024.png`,
    restroomMarble: `${supplied}/textures/restroom/restroom1_marble png.png`,
    restroomMarbleDark: `${supplied}/textures/restroom/restroom1_marble png2.png`,
    restroomTowelDispenser: `${supplied}/textures/restroom/restroom1_towel dispenser base.png`,
    restroomMetalSheet: `${supplied}/textures/restroom/restroom1_metal sheet albedo darker.png`,
    restroomDoor: `${supplied}/textures/intro/restroom1_metal door.png`,
    waiverPaper: `${supplied}/textures/intro/signature machine2_release form1.png`,
    waiverMetal: `${supplied}/textures/intro/signature machine2_base metal keyboard.png`,
    waiverKeyboard: `${supplied}/textures/intro/signature machine2_keyboard base.png`,
  },
};
